### ISSUE TITLE
project is not up to date with the latest emarsys specification

### ISSUE THREAD

**Issue by adamluzsi** [EscherAuth/escher#5]
- [ ] TestGetStringToSign/emarsys_testsuite/signrequest-date-header-should-be-signed-headers.json
- [ ] TestGetStringToSign/emarsys_testsuite/signrequest-signedheaders-downcase.json
- [ ] TestGetStringToSign/emarsys_testsuite/signrequest-support-custom-config.json
- [ ] TestGenerateHeader/emarsys_testsuite/signrequest-signedheaders-downcase.json
- [ ] TestGenerateHeader/emarsys_testsuite/signrequest-support-custom-config.json
- [ ] TestCanonicalizeRequest/emarsys_testsuite/signrequest-date-header-should-be-signed-headers.json
- [ ] TestCanonicalizeRequest/emarsys_testsuite/signrequest-signedheaders-downcase.json
- [ ] TestCanonicalizeRequest/emarsys_testsuite/signrequest-support-custom-config.json
- [ ] TestSignRequest_RequestIsValid_SignedRequestReturned/emarsys_testsuite/signrequest-date-header-should-be-signed-headers.json
- [ ] TestSignRequest_RequestIsValid_SignedRequestReturned/emarsys_testsuite/signrequest-get-with-carets.json
- [ ] TestSignRequest_RequestIsValid_SignedRequestReturned/emarsys_testsuite/signrequest-get-with-parentheses.json

**Comment by adamluzsi** [comment]
@szeist can we do pair programming on this one? (After your holiday)

**Comment by szeist** [comment]
Sure!

**Comment by adamluzsi** [comment]
Is this issue still relevant @szeist ?

**Comment by szeist** [comment]
I think we can close this now and review it later with the other integrations.

**Comment by adamluzsi** [comment]
Yes, it's kinda orphaned task. Can you show me what's the latest greatest testing suit to test client a implementation?

**Comment by szeist** [comment]
We’re still using the test cases in this org.:
https://github.com/EscherAuth/test-cases

**Comment by adamluzsi** [comment]
I just checked out the latest greatest commit from the test-cases repo.
Since everything is passing with the latest testing suite, I close the issue as requested! : )

Cheers!
